### PR TITLE
Identity: unsets field 'password' in data

### PR DESCRIPTION
**Pull request by dg**

### CODE REVIEW

**Comment by fprochazka** [comment]
:-1:

**Comment by nechutny** [comment]
That's programmer choice if he save password to identity data. There are regular use-cases, when field 'password' is ok. For example I want know, if is user authenticated via password, or openId. Of course, one can admit, that filed named 'password' isn't good name, but that's just example, that force unseting this field isn't good.

**Comment by fprochazka** [comment]
@nechutny :+1:

**Comment by enumag** [comment]
:-1:

**Comment by Majkl578** [comment]
:-1:

**Comment by milo** [comment]
I don't like such silent actions. What about `E_WARNING` and `Identity::$letLeakPassword = TRUE` ?

**Comment by Majkl578** [comment]
Just put it into documentation with an exclamation mark.

**Comment by dg** [comment]
Yes, it is not „academically clean“, in fact, it is ugly, it is uglier than silent trimming strings from text inputs.

**Comment by milo** [comment]
What's the reason anyway? Is there more reasons than prevent dumping and storing into session? The sandbox `unset()` is not enought?

Trimming text input is a reasonable sanitization of input values. This is user's datastructure changing.

**Pull request closed without merging**
