### PR TITLE
UserStorage: support int in setExpiration() (3.1)

### PR DESCRIPTION
**Pull request by dakur**
backport of #71 to v3.1

### CODE REVIEW

**Comment by dg** [comment]
It is simply not possible to change signatures for interface methods because of backward compatibility.

**Comment by dakur** [comment]
Why? The type is widened, not narrowed, so it is backward compatible. Or do I overlook something?

**Comment by mabar** [comment]
Only final implementations can safely widen accepted types. Doing so in extendable methods and interfaces is BC break, because implementations have to do it too.

**Comment by dakur** [comment]
Aha, thanks for explanation.. So I'm closing this and leave only #71

**Pull request closed without merging**
