### PR TITLE
Using named parameters instead of $credentials

### PR DESCRIPTION
**Pull request by 2bad2furious**
Why wasn't this done in the first place?

- bug fix? no   
- new feature? no
- BC break? yes

I honestly don't fully understand the decision-making during this, I don't think this method is being used anywhere else.

### CODE REVIEW

**Comment by lukaspijak** [comment]
Do you think that all authenticators work on a name and password basis? Please reject this PR.

**Comment by milo** [comment]
@2bad2furious The username and password are not the only one. In some of my cases, I work with domain too.

**Comment by 2bad2furious** [comment]
Thank you @lukaspijak for coming here with an open mind :). I want to start a discussion.. I don't think it's pretty to use `func_get_args()` in general. All you need for custom loggin in (meant with other credentials than username & password) is to write a custom method, as far as i know, everything happening in `login()` can be done manually outside the User class.

**Comment by 2bad2furious** [comment]
I agree, this is probably better than my original solution.

The original idea was done with 3.0 being kind of independent with a whole lot of BC happening. Or at least I heard it would be.

**Pull request closed without merging**
