### PR TITLE
User: Add shortcut for isAdmin().

### PR DESCRIPTION
**Pull request by janbarasek**
- new feature
- BC break? no

Just smart shortcut.

### CODE REVIEW

**Comment by mabar** [comment]
Isn't it better to leave it in your app/library? For anyone who don't have role admin defined it does not make sense.

**Comment by janbarasek** [comment]
Yes, I understand it. On the other hand, some libraries require the role of `admin`, others `root`, another `Admin` and so on. Nette could normalize that.

**Comment by mabar** [comment]
And some have roles created by system admins and they assign permissions to these roles. In that case any role checks don't make sense at all, as they are dynamic. And it's better for administrators because roles can reflect structure of organization instead of what programmer hardcoded.

**Comment by janbarasek** [comment]
ok

**Pull request closed without merging**
